### PR TITLE
add global bamboo texture

### PR DESCRIPTION
**Pull request by mbruchert**

### CODE REVIEW

**Comment by jbruechert** [comment]
Thanks. I assume it's already tested?

**Comment by lnjX** [comment]
Are the textures  optimized (using advpng and optipng)?

**Comment by mbruchert** [comment]
no they aren't...

**Comment by lnjX** [comment]
Could you do that? Just use `optipng -o7 *.png` and `advpng -z4 *.png`.

The required debian packages are `optipng` and `advancecomp`.

**Pull request merged**
